#### creating the ec2 instnce and updatin the route 53 DNS records


- name: creatin the ec2 instance and r53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    security_group_id: sg-0e26bb3210120668f
    zone_id: "us-east-1"
    domain_name: cloudquestdev.com
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ security_group_id }}"
      image_id: "{{ ami_id }}"
      tags:
        name: "{{ item }}"
      
    loop: "{{ instances }}"
    register: ec2_output
  
  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"
